### ISSUE TITLE
Problems with choosing my name

### ISSUE THREAD

**Issue by ShadyMedic** [ajjj001/Exported-Whatsapp-Chat-Viewer#1]
The website looks really nice, but when I upload the text file and should choose my name, it shows only the first sender and it's bound with the time and date. For example, the beginning of my `.txt` export file looks like this:
`23.10.20 22:49 - MyName: ‎IMG-20201023-WA0017.jpg (soubor byl přiložen)`
and after I upload it, the prompt shows just one option: 
![Screenshot](https://user-images.githubusercontent.com/19894267/104891639-83106b80-5971-11eb-968d-1bb7c59707d7.png).

As a result, the whole export is like just one message and is on a single line.

**Comment by ajjj001** [comment]
Thanks for letting me know. I wasn't aware that the Android exports were different, I've now fixed it and please let me know if you still have any issues.

**Comment by ShadyMedic** [comment]
Works great! Thank you!

But I've noticed another, less severe issue. For some reason, one of the messages is also displayed in the name selection:
![image](https://user-images.githubusercontent.com/19894267/104929038-ad7b1c80-59a3-11eb-8197-7c1656b655eb.png)

This is how the part of the file with that message looks like:
```
01.01.21 18:34 - MyName: My Message
01.01.21 18:40 - MyName: Kinda Long Message Spreading On Multiple Lines

I got some pretty neat gifts. My brother bought me Fallout 3 - Rest Of My Message
07.01.21 16:47 - MyFriend'sName: My Friend's Message 🤍
```
I guess that the dash is causing the problem.
