### ISSUE TITLE
Contents after a line break in the message is not displayed

### ISSUE THREAD

**Issue by reembar** [ajjj001/Exported-Whatsapp-Chat-Viewer#2]
Hi. Your chat viewer is the best I found.
In the Whatsapp Android app you can press Enter for a line-break, without sending the message.
When I export my chat from an Android phone and upload it to your script - every time there are line breaks in a message, only the first line of this message is displayed, and everything written in this message after the line break is ignored.
Thanks for your great script!

**Comment by ajjj001** [comment]
Hey, I'm glad you found this useful, and I appreciate your feedback. 

I've actually written a new parser, and I'm currently developing a new front end. I'm a little busy right now, but I'll release it as soon as I'm done.
